### ISSUE TITLE
missing readme steps of windows and esp partitions 

### ISSUE THREAD

**Issue by abhayjod** [graphiks/woa-raphael#1]
i guess there is a typo at step 1.2
(parted) mkpart esp fat32 32GB 32.5GB
# set the esp partition as `EFI system partition type`
(parted) set 23 esp on
# partition for installing Windows
(parted) mkpart win ntfs 32.5GB 122GB

**Comment by graphiks** [comment]
I remember writing these steps. I somehow forgot to save these changes, thanks for the contribution
